sandbox_image: "fireenv-sandbox:latest"
container_prefix: "fireenv-sandbox"
persistent_storage_path: "/persistent"
cpu: 1
memory: "1g"
timeout: 60
docker_host: "unix://var/run/docker.sock"
debug: false
log_level: "INFO"
max_retries: 3
retry_delay: 1.0
